#!/bin/sh
# File generated by ocamlbuild

cd /home/wonton/Documents/emojiirc

rm -f emoji.cmi
rm -f emoji.cmx
rm -f emoji.o
# Also clean the script itself
rm -f /home/wonton/Documents/emojiirc/_build/sanitize.sh
